-- This script is used for initializing a new embedded H2 admin database.

-- RUNSCRIPT FROM 'classpath:/com/acme/test.sql'



/*
DROP TABLE IF EXISTS QTE_T_EDITOR2TABLE;
DROP TABLE IF EXISTS QTE_T_TABLE;
DROP TABLE IF EXISTS QTE_T_DATASOURCE;
DROP TABLE IF EXISTS QTE_T_USER;
*/


CREATE TABLE IF NOT EXISTS QTE_T_USER (
    USER_ID NUMBER(6) AUTO_INCREMENT(1) PRIMARY KEY,
    LOGIN_NAME VARCHAR2(40) NOT NULL UNIQUE,
    USER_NAME VARCHAR2(200),
    SALT VARCHAR2(4),
    SALTED_MD5 VARCHAR2(32),
    ADMIN BOOLEAN DEFAULT FALSE,
    DISABLED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS QTE_T_DATASOURCE (
    DS_ID NUMBER(6) AUTO_INCREMENT(1) PRIMARY KEY,
    DS_NAME VARCHAR2(200) NOT NULL UNIQUE,
    JDBC_DRIVER VARCHAR2(200) NOT NULL,
    JDBC_URL VARCHAR2(4000) NOT NULL,
    USERNAME VARCHAR2(200),
    PASSWORD VARCHAR2(200),
    DISABLED BOOLEAN DEFAULT FALSE
);



CREATE TABLE IF NOT EXISTS QTE_T_TABLE (
    TABLE_ID NUMBER(8) AUTO_INCREMENT(1) PRIMARY KEY,
    DS_ID NUMBER(6),
    TABLE_SCHEMA VARCHAR2(200),
    TABLE_NAME VARCHAR2(200) NOT NULL,
    TABLE_TITLE VARCHAR2(200) NOT NULL,
    TABLE_DESC VARCHAR2(4000),
    DISABLED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY(DS_ID) REFERENCES QTE_T_DATASOURCE(DS_ID)
);

CREATE TABLE IF NOT EXISTS QTE_T_T2U (
    T2U_ID NUMBER(12) AUTO_INCREMENT(1) PRIMARY KEY,
    TABLE_ID NUMBER(8),
    USER_ID NUMBER(6),
    FOREIGN KEY(TABLE_ID) REFERENCES QTE_T_TABLE(TABLE_ID),
    FOREIGN KEY(USER_ID) REFERENCES QTE_T_USER(USER_ID)
);

insert into QTE_T_USER (LOGIN_NAME, USER_NAME, SALT, SALTED_MD5, ADMIN, DISABLED) values ('admin', 'Administrator', 'FF00', '5D720FBFE9664A90175FDABB1D917CE0', true, false);

commit;



