-- This script is used for initializing a new embedded H2 admin database.

-- RUNSCRIPT FROM 'classpath:/com/acme/test.sql'



/*
DROP TABLE IF EXISTS QTE_T_EDITOR2TABLE;
DROP TABLE IF EXISTS QTE_T_TABLE;
DROP TABLE IF EXISTS QTE_T_DATASOURCE;
DROP TABLE IF EXISTS QTE_T_USER;
*/


CREATE TABLE IF NOT EXISTS QTE_T_USER (
    USER_ID NUMBER(6) AUTO_INCREMENT(1) PRIMARY KEY,
    LOGIN_NAME VARCHAR2(20) NOT NULL UNIQUE,
    USER_NAME VARCHAR2(200),
    SALT VARCHAR2(4),
    SALTED_MD5 VARCHAR2(32),
    ADMIN BOOLEAN DEFAULT FALSE,
    DISABLED BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS QTE_T_DATASOURCE (
    DS_ID NUMBER(6) AUTO_INCREMENT(1) PRIMARY KEY,
    DS_NAME VARCHAR2(200) NOT NULL UNIQUE,
    JDBC_DRIVER VARCHAR2(200) NOT NULL,
    JDBC_URL VARCHAR2(4000) NOT NULL,
    USERNAME VARCHAR2(200),
    PASSWORD VARCHAR2(200),
    DISABLED BOOLEAN DEFAULT FALSE
);



CREATE TABLE IF NOT EXISTS QTE_T_TABLE (
    TABLE_ID NUMBER(8) AUTO_INCREMENT(1) PRIMARY KEY,
    DS_ID NUMBER(6),
    TABLE_SCHEMA VARCHAR2(200) NOT NULL,
    TABLE_NAME VARCHAR2(200) NOT NULL,
    TABLE_TITLE VARCHAR2(200) NOT NULL,
    TABLE_DESC VARCHAR2(4000),
    DISABLED BOOLEAN DEFAULT FALSE,
    FOREIGN KEY(DS_ID) REFERENCES QTE_T_DATASOURCE(DS_ID)
);

CREATE TABLE IF NOT EXISTS QTE_T_T2U (
    T2U_ID NUMBER(12) AUTO_INCREMENT(1) PRIMARY KEY,
    TABLE_ID NUMBER(8),
    USER_ID NUMBER(6),
    FOREIGN KEY(TABLE_ID) REFERENCES QTE_T_TABLE(TABLE_ID),
    FOREIGN KEY(USER_ID) REFERENCES QTE_T_USER(USER_ID)
);

insert into QTE_T_USER (USER_NAME, PWD_MD5, IS_ADMIN) values ('admin', '21232F297A57A5A743894A0E4A801FC3', true);
insert into QTE_T_DATASOURCE (DS_NAME, JDBC_DRIVER, JDBC_URL) values ('qte-master-db', 'org.h2.Driver', 'jdbc:h2:~/.quick-table-editor/config');
insert into QTE_T_TABLE (DS_ID, TABLE_NAME, TABLE_TITLE) values (1, 'QTE_T_TABLE', 'QTE User Definition Table');
insert into QTE_T_EDITOR2TABLE (TABLE_ID, USER_ID) values (1, 1);

commit;



