package com.ct.ks.bsc.qte.core;

/**
 *
 * @author xma11
 *
 */
public interface Constants {

    String CONFIG_H2_JDBC_DRIVER = "org.h2.Driver";
    String CONFIG_H2_JDBC_URL = "jdbc:h2:~/.quick-table-editor/config";
    String EXTRA_JDBC_LIB_DIR = "~/.quick-table-editor/jdbc";
    String MASTER_DATASOURCE_NAME = "qte-master-db";
    String SQL_GET_TABLE_COUNT = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='PUBLIC'";
    String INIT_DB_SQL_FILENAME = "init-db.sql";
    String CONFIG_TABLE_USER = "QTE_T_USER";
    String CONFIG_TABLE_CONN = "QTE_T_DATASOURCE";
    String CONFIG_TABLE_TABLE = "QTE_T_TABLE";
    String CONFIG_TABLE_EDITOR2TABLE = "QTE_T_EDITOR2TABLE";

    String META_COL_TYPICAL_NAME_TABLE_SCHEM = "TABLE_SCHEM";
    String META_COL_TYPICAL_NAME_TABLE_NAME = "TABLE_NAME";
    String META_COL_TYPICAL_NAME_COLUMN_NAME = "COLUMN_NAME";
    String META_COL_TYPICAL_NAME_DATA_TYPE = "DATA_TYPE";
    String META_COL_TYPICAL_NAME_TYPE_NAME = "TYPE_NAME";
    String META_COL_TYPICAL_NAME_COLUMN_SIZE = "COLUMN_SIZE";
    String META_COL_TYPICAL_NAME_DECIMAL_DIGITS = "DECIMAL_DIGITS";
    String META_COL_TYPICAL_NAME_NULLABLE = "NULLABLE";
    String META_COL_TYPICAL_NAME_REMARKS = "REMARKS";
    String META_COL_TYPICAL_NAME_COLUMN_DEF = "COLUMN_DEF";
    String META_COL_TYPICAL_NAME_IS_AUTOINCREMENT = "IS_AUTOINCREMENT";
}
